//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Routing;
    using Itenso.TimePeriod;
    using static System.Data.Entity.Infrastructure.Design.Executor;

    public partial class Order_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Book()
        {
            this.Return_Book = new HashSet<Return_Book>();
        }
    
        public int Order_Id { get; set; }
        [Required]
        public Nullable<int> user_id { get; set; }
        [Required]
        public string Book_Name { get; set; }
        [Required]
        public Nullable<System.DateTime> Issue_Date { get; set; }

        public Nullable<System.DateTime> Return_Date { get; set; }

        public virtual Book Book { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Return_Book> Return_Book { get; set; }
    }
}
