//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Return_Book
    {
        public int Return_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public string Book_Name { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public Nullable<int> Elapse { get; set; }
        public Nullable<int> Fine { get; set; }
    
        public virtual Order_Book Order_Book { get; set; }
    }
}
